import { Fredoka } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Fredoka({ subsets: ["latin"] });

export const metadata = {
  title: "Rakib",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`w-full  h-full  flex flex-col bg-[#122033] text-white md:flex-row gap-5  ${inter.className}`}
      >
        <div className="w-full md:w-[15%] md:h-screen md:fixed border-r-2 border-[#2A2C39]">
          <Sidebar/>
        </div>
        <div className="w-full md:w-[85%] ml-0 md:ml-[15%]">{children}</div>
      </body>
    </html>
  );
}
